install.packages("sp", dependencies=TRUE)
install.packages("raster", dependencies=TRUE)
install.packages("rgdal", dependencies=TRUE)
install.packages("rgeos", dependencies=TRUE)
install.packages("dismo", dependencies=TRUE)
install.packages("maptools", dependencies=TRUE)
install.packages("ggmap", dependencies=TRUE)